First commit
sserwangaedrisa/Books-library pull request #1
Opened 2023-08-30 12:43 UTC by sserwangaedrisa

HERE ARE THE CHANGES MADE IN THIS COMMIT
1. Writing the html code without the navigation bar
2. Styling the written html using the style.css file
3. Adding a javascript file (style.js) that allows the users to add and remove the books from the library
4. Styling the added books list to match the found books

2023-08-31 20:17 UTC, arnoldnekemiah requested changes
You have done alot to present your work the best way you can but their are a number of changes you have to make to complete this milestone. :cry: 

1.Next time when creating a pull request, you name it according to the project that you are doing.FOr every new milestone of the project you will create a new branch.For now You can keep this thread.
2. Code not presented to standard. Click here to learn how to configure linters into your project, and learn how to use them to correct your work syntax.
3. The approach you have used to do this activity is wrong.
Below is a list of Links to teach you how Object-method works 

- [Object literal notation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer)
- [Object() constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/Object).
- [Object.prototype.constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor).
- [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create).
[Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

4. Also consider learning how Local storage works.

Please try again and submi this very pull request.

2023-09-02 12:53 UTC, sserwangaedrisa commented on style.css
> +}
I did not manage using linters but i used another code formatter called prettier to try solving that issue

2023-09-02 12:54 UTC, sserwangaedrisa commented on style.js
> +// }
i removed all the commented code from my  work

2023-09-02 12:55 UTC, sserwangaedrisa commented on style.js
> +
i minimized the usage of var. And now i know the difference between the two words

2023-09-02 12:55 UTC, sserwangaedrisa commented on style.js
> +    // console.log(title.value)
removed

2023-10-05 09:31 UTC, closed without merging